skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: '' # latest
    - nodejs_version: '12'
    - nodejs_version: '10'

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm ci

build_script:
  - npm run lint
  - npm run build

before_test:
  - git config --global user.email "test@testy.com"
  - git config --global user.name "Test testy"
  - git --version

test_script:
  - npm test
